ALTER TABLE `chamadas`
  MODIFY `turno` ENUM(
    'MATUTINO',
    'INTEGRAL',
    'NOTURNO',
    'UNIGRAN_MATUTINO_INTEGRAL',
    'UFGD_MATUTINO_INTEGRAL',
    'UFGD_TRANSLADO_MATUTINO_11H',
    'UNIGRAN_NOTURNO',
    'IFMS_MATUTINO',
    'UFGD_NOTURNO'
  ) NOT NULL;

ALTER TABLE `viagens`
  MODIFY `turno` ENUM(
    'MATUTINO',
    'INTEGRAL',
    'NOTURNO',
    'UNIGRAN_MATUTINO_INTEGRAL',
    'UFGD_MATUTINO_INTEGRAL',
    'UFGD_TRANSLADO_MATUTINO_11H',
    'UNIGRAN_NOTURNO',
    'IFMS_MATUTINO',
    'UFGD_NOTURNO'
  ) NULL;
