import { Router } from 'express';
import * as controller from '../controllers/ocorrencia.controller.js';
import { authenticate } from '../middlewares/auth.middleware.js';
import { validate } from '../middlewares/validate.middleware.js';
import { listOcorrenciasSchema, ocorrenciaIdSchema, updateOcorrenciaSchema } from '../validators/ocorrencia.validator.js';
const router = Router();
router.use(authenticate);
router.get('/', validate(listOcorrenciasSchema), controller.list);
router.get('/:id', validate(ocorrenciaIdSchema), controller.findById);
router.put('/:id', validate(updateOcorrenciaSchema), controller.update);
export default router;
