export const LEGACY_SHIFT_VALUES = ['MATUTINO', 'INTEGRAL', 'NOTURNO'];

export const TRANSPORT_SHIFT_VALUES = [
  'UNIGRAN_MATUTINO_INTEGRAL',
  'UFGD_MATUTINO_INTEGRAL',
  'UFGD_TRANSLADO_MATUTINO_11H',
  'UNIGRAN_NOTURNO',
  'IFMS_MATUTINO',
  'UFGD_NOTURNO',
];

export const ALL_SHIFT_VALUES = [...LEGACY_SHIFT_VALUES, ...TRANSPORT_SHIFT_VALUES];

export const TRANSPORT_SHIFT_LABELS = {
  MATUTINO: 'Matutino (registro antigo)',
  INTEGRAL: 'Integral (registro antigo)',
  NOTURNO: 'Noturno (registro antigo)',
  UNIGRAN_MATUTINO_INTEGRAL: 'UNIGRAN MATUTINO/INTEGRAL',
  UFGD_MATUTINO_INTEGRAL: 'UFGD MATUTINO/INTEGRAL',
  UFGD_TRANSLADO_MATUTINO_11H: 'UFGD TRANSLADO MATUTINO (11h)',
  UNIGRAN_NOTURNO: 'UNIGRAN NOTURNO',
  IFMS_MATUTINO: 'IFMS MATUTINO',
  UFGD_NOTURNO: 'UFGD NOTURNO',
};
